services:
  - type: static
    name: digital-equb-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://digital-equb-api.onrender.com
  - type: web
    name: digital-equb-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: EMAIL_USER
        value: yerosang463@gmail.com
      - key: EMAIL_PASS
        value: xgyb rmcz hcqr jixr
      - key: ADMIN_EMAIL
        value: yerosang463@gmail.com
