services:
  - type: web
    name: digital-equb-frontend
    env: static
    rootDir: frontend
    buildCommand: npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://digital-equb-api.onrender.com
      - key: VITE_GOOGLE_CLIENT_ID
        value: 429331269650-603npcn5lessg06j4se2vbqejmv5tq3g.apps.googleusercontent.com
  - type: web
    name: digital-equb-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: EMAIL_USER
        value: yerosang463@gmail.com
      - key: EMAIL_PASS
        value: xgyb rmcz hcqr jixr
      - key: ADMIN_EMAIL
        value: yerosang463@gmail.com
