services:
  - type: web
    name: digital-equb-frontend
    env: static
    rootDir: frontend
    buildCommand: npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://digital-equb-2.onrender.com
      - key: VITE_GOOGLE_CLIENT_ID
        value: 242581177542-vgr5gqkck30oeje3jt52t1aq4s0664p9.apps.googleusercontent.com
