services:
  - type: web
    name: digital-equb-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: sql208.infinityfree.com
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: if0_41755694
      - key: DB_PASSWORD
        value: Yero27101620
      - key: DB_NAME
        value: if0_41755694_digitalequb
      - key: JWT_SECRET
        value: digital-equb-jwt-secret-key-2024
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
    plan: free
