services:
  - type: web
    name: digital-equb-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: sql12824412
      - key: DB_PASSWORD
        value: buUvLxRXXv
      - key: DB_NAME
        value: sql12824412
      - key: JWT_SECRET
        value: digital-equb-jwt-secret-key-2024
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: GOOGLE_CLIENT_ID
        value: 640189153673-g3aeovpv6shim22e4r2s5ijr14ffqkpl.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
    plan: free
